### ISSUE TITLE
Always on top

### ISSUE THREAD

**Issue by platinumsam** [tabfloater/tabfloater#232]
Hello,
It wouldn't be a bad idea to have an option (in preferences) to keep the floating window always on top of the other tabs, not system wide just in Firefox.
By the way this extension is great.
Thank you.

**Comment by ba32107** [comment]
Hi @platinumsam, let me just check if I understand you correctly. The floating window _should_ stay on top of your other tabs - this is how the extension is designed.

However, I think what you mean is, if you have multiple Firefox windows open, then the floating window will stay on top of only one of them, right? Sadly I think implementing your suggestion is not possible. We basically have two options: we either make the floating window a "child window" of your main browser (this is how it works now), or we can make it always on top (of every single window in your system). There's no way to make it always on top of just _some_ windows.

We already have https://github.com/tabfloater/tabfloater/issues/231 to track the "always on top of everything" feature.

**Comment by platinumsam** [comment]
Hello,
     Thank you for prompt reply. I'm using latest Firefox on 2020 MacBook 16, Big Sur. When I float a tab, and when I click on the tab right behind it, the floating tab goes away, until I click on the extension button in the toolbar, then it (the floating tab) goes back to how it was before I floated it. If that's what's supposed to happen, then maybe I'm wrong.

Thank you,
Sam.

**Comment by ba32107** [comment]
Ah okay, I understand now. No, that's not supposed to happen - in fact, the point of this app is to prevent that :) That's why you would need to install the [Companion](https://www.tabfloater.io/documentation#why-do-i-need-to-install-an-application-on-my-computer-to-use-tabfloater). 

Unfortunately, in your case, this won't work because the Companion is unavailable on MacOS. I personally don't have the means to implement that - hopefully, someone else will take up the opportunity. 

This is tracked in https://github.com/tabfloater/tabfloater/issues/189, please keep an eye on that issue.
