### ISSUE TITLE
When minimize button is clicked the window disappears

### ISSUE THREAD

**Issue by RandallFlagg** [tabfloater/tabfloater#258]
## Description
[NOTE]: # ( Describe the problem below. What are you doing when the problem occurs? What would you expect to happen? What actually happens? )
When minimize button is clicked the window disappears

## Reproduction steps
[NOTE]: # ( Provide an exact set of steps to reproduce this issue. Please be as detailed as you can. )
[NOTE]: # ( Start each step with "1." as you see below, it will be rendered as a numbered list. )
[TIP]:     # ( Provide a screenshot if you can. You can paste an image into this text box. )
 1. Install the extension and the companion
 2. Choose a tab and push the "Float tab!" button in the browser
 3. Minimize the window using the minus button on the floating tab

**Expected:** Find the window and maximize it
**Actual:** Can't find the window so can't maximize it

## Environment
[NOTE]: # ( Provide information about your machine and environment. )
[NOTE]: # ( For "Companion installation", specify how you installed the Companion. E.g. for Windows: installer/portable, for Linux: AppImage/PPA )
 * **TabFloater version:** 1.1.0
 * **Companion version:** 1.1.0
 * **Operating system:** Win 10 x64
 * **Browser**: Chromium Based
 * **Companion installation:** Portable

**Comment by ba32107** [comment]
Hi,

This is actually by design. TabFloater will remove the floating tab's window from your taskbar. This is supposed to make the floating tab more "panel-like" - it's supposed to be a small panel within the main browser window (you'll notice that, if you minimize the main browser window, the floating tab is also minimized along with the main one).

That being said, I understand the confusion because if you do minimize the floating tab, getting it back is not straightforward. I actually think the proper solution would be to prevent minimizing the floating tab - however, I don't know from the top of my head if this is possible or not. I will have a look. If I cannot, then I can remove the code which hides the floating tab window from the taskbar.

I'll get on this as soon as I have some time.

**Comment by ba32107** [comment]
Hi,

This is now done. You will get the update in the next few days. You'll need to download a new companion version here:
https://www.tabfloater.io/download

Thanks
