### ISSUE TITLE
"The error message was: Pro subscription is not active"

### ISSUE THREAD

**Issue by kostasvl** [tabfloater/tabfloater#296]
Trying to launch the companion, I get a windows notification saying "Please subscribe to use Tabfloater". On the options page, the Status for the companion says Unavailable, followed by "... The error message was: Pro subscription is not active". The new Sign In button at the top takes me to https://tabfloater-3b3a5.web.app/, which seems suspicious. Worse is the fact that I see no mention of a new Pro subscription, on either the website (https://www.tabfloater.io/), this github page, or the chrome extension store (https://chromewebstore.google.com/detail/tabfloater-picture-in-pic/iojgbjjdoanmhcmmihbapiejfbbadhjd)

Is this all legit (minus the missing documentation on the new subscription), or has this extension been hacked? The current version is 2.0.0 apparently, which was updated yesterday. It asked for a new permission: to show notifications...

EDIT:
![image](https://github.com/user-attachments/assets/ddfa7dd8-ec7d-473d-b6fc-83a066daf843)

**Comment by JusstewaSNSJ** [comment]
Hi kostasvl,

Thanks for reaching out. Yes, the change is legitimate. I'll address your comments individually, and provide an explanation for the change:

1. Regarding the web.app address: I have escalated this issue to Firebase because it is supposed to display the "tabfloater.io" domain. The URL you're seeing now is the Firebase-generated address. For context, the authentication code is hosted on Firebase and routes any payment information directly to Stripe to ensure user data remains secure. We do not store any of that information on our end.
2. The notification permission is a Chrome requirement. Since the extension is communicating with the companion application during the authentication flow, we were required to include that in the latest package uploaded to the Chrome webstore. Additionally, existing users needed to be notified of the change, and the only way to do that since there were no emails provided previously was to send out push notifications.
3. Regarding the documentation, we had to update the license from an Apache License to an official End User License Agreement, as TabFloater is no longer an open source tool. Once that change has been verified by GitHub, all of the documentation changes will reflect that accordingly.

TabFloater has been free for the last four years, and we’re grateful for all the support from users like you. However, to continue providing a reliable service and introduce new features we’ve been working on, we’ve had to make the switch to a subscription model.

This decision was also driven by rising infrastructure costs. By requiring an account and subscription, we can ensure TabFloater remains sustainable while we roll out some exciting updates like multiple floating tabs and enhanced productivity tools.

We greatly appreciate your support, and want to ensure we continue providing the best tool for our users. Please send me an email at justin@tabfloater.io, and I can send you a code to redeem for 2-free months of TabFloater Pro.

Best,
Justin

**Comment by kostasvl** [comment]
Hi Justin. Thanks for the explanation. I'm glad it wasn't a hack you guys suffered, but I'm also sad I can't use the extension any more without paying. Your website makes it clear that the Always On Top feature is basically the whole point, so I don't see the Basic version being very useful to most people.

I wish you would only put future new features behind a paywall, and not the very core of the extension... Especially since the core is already working and doesn't need much maintenance, right? Anyway, it is your decision of course.

Oh well, it was fun while it lasted. I'm definitely grateful for the value I got out of this extension, so thank you for releasing it to the world for free, at first. I'll do some research in the extensions store again, though I suspect I'll have to come back to TabFloater and become a subscriber. We'll see.

**Comment by JusstewaSNSJ** [comment]
Hi kostavl,

I appreciate the feedback. We had a lengthy discussion regarding the features included in Basic vs. Pro access, and we ultimately decided to implement the new configuration based on what our user feedback and analytics told us about feature usage.

A good percentage of the user base wasn't using the Always On Top feature primarily because they couldn't download the companion application on the device they used TabFloater on. For example, they use TabFloater on a work computer and their organization's IT department doesn't allow non-approved, native applications, like the companion app, to be downloaded.

We're sorry to lose you as a user. If you do decide to come back to us, send me an email at justin@tabfloater.io and I'd be happy to honor the discount I mentioned in my previous comment.

Best,
Justin
